#!/bin/bash

source ~/.profile

echo Stopping tomcat
sudo /usr/sbin/service tomcat7 stop 

echo Recursive change ownership of geoserver data directory to tomcat7:tomcat7

sudo /bin/chown -R tomcat7 ${HOME}/ltfri/geoserver/data
sudo /bin/chgrp -R tomcat7 ${HOME}/ltfri/geoserver/data

echo Recuirsive change mode of geoserver data directory to allow write access by user and group
sudo /bin/chmod -R ug+w ${HOME}/ltfri/geoserver/data

echo Starting tomcat
sudo /usr/sbin/service tomcat7 start
