module.exports = [].concat(
  require('./home'),
  require('./search'),
  require('./risk'),
  require('./risk-detail'),
  require('./risk-types'),
  require('./map'),
  require('./feedback'),
  require('./statics'),
  require('./gwc-proxy'),
  require('./banner'),
  require('./os-get-capabilities'),
  require('./api/geocode'),
  require('./england-only'),
  require('./404'),
  require('./os-terms'),
  require('./error'),
  require('./echo')
)
